spring.jackson.serialization.INDENT_OUTPUT=true

# include health endpoint at http://localhost/actuator/health
management.endpoint.metrics.enabled=true
management.endpoints.web.exposure.include=health, metrics
management.endpoint.health.show-details=always
# set base path to be  "/"
server.servlet.context-path=/

#management.endpoints.web.exposure.exclude=health
