info:
  app:
    description: RouteScout Spring Boot API
    name: routescout
    version: 1.0.0
management:
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: openapi, swagger-ui
google:
  maps:
    key: ${GOOGLE_MAPS_API_KEY:YOUR_MAPS_KEY}
  gemini:
    key: ${GOOGLE_API_KEY:YOUR_GEMINI_KEY}
server:
  port: 5001
spring:
  application:
    name: routescout
  datasource:
    password: YOUR_DB_PASSWORD
    url: jdbc:postgresql://YOUR_DB_URL:YOUR_DB_PORT/YOUR_DEFAULT_DB
    username: YOUR_DB_USER
  mvc:
    servlet:
      load-on-startup: 1
  profiles:
    active: '@spring.profiles.active@'
springdoc:
  packagesToScan: edu.citadel.api
  pathsToMatch: /v1, /**
  show-actuator: true
