info:
  app:
    description: RouteScout Spring Boot API
    name: routescout
    version: 1.0.0
management:
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: openapi, swagger-ui
google:
  maps:
    key: ${GOOGLE_MAPS_API_KEY:my_api_key}
server:
  port: 5001
spring:
  application:
    name: routescout
  datasource:
    password: my_pwd
    url: jdbc:postgresql://my_db:my_port/my_user?sslmode=require
    username: my_user
  mvc:
    servlet:
      load-on-startup: 1
  profiles:
    active: '@spring.profiles.active@'
springdoc:
  packagesToScan: edu.citadel.api
  pathsToMatch: /v1, /**
  show-actuator: true
